execution:
- concurrency: 1
  hold-for: 2m
  ramp-up: 1m
  steps: 1
  scenario:
    script: ../scripts/testscript.jmx
    data-sources:
      - ../datafiles/testDataFilePt.csv
settings:
  check-interval: 5s
  default-executor: jmeter